[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
# runner = 'arm-none-eabi-gdb'
runner = 'probe-run --chip ATSAMD21G18AU'
# runner = 'probe-run --chip ATSAMD21G18AU'

# ATSAMD21G18AU

# rustflags = [

#   # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
#   # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
#   "-C", "link-arg=--nmagic",
  
#   "-C", "link-arg=-Tlink.x",
# ]

rustflags = [  
  "-C", "linker=arm-none-eabi-gcc",
#   "-C", "link-arg=--nmagic",
#   "-C",  "linker=lld",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-Wl,--print-memory-usage",
  "-C", "link-arg=-Wl,-Map=out.map",
  "-C", "link-arg=-Wl,--verbose",
  "-C", "save-temps",
  "--emit", "asm",
]


# rustflags = [

#   # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
#   # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
#   "-C", "link-arg=--nmagic",
  
#   "-C", "link-arg=-Tlink.x",
# ]